on:
  push:
    branches:
      - main
env:   
   AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY}}    
   AWS_SECRET_ACCESS_KEY:  ${{secrets.SECRET_ACCESS_KEY}}

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: format
        run: terraform fmt -check  

      - name: Plan Terraform
        run: terraform plan    

      